/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as RgpdRouteImport } from './routes/rgpd'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as AtualizacoesRouteImport } from './routes/atualizacoes'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PainelSuporteRouteImport } from './routes/painel.suporte'
import { Route as PainelDefinicoesRouteImport } from './routes/painel.definicoes'
import { Route as PainelClientesRouteImport } from './routes/painel.clientes'
import { Route as PainelAssinaturaRouteImport } from './routes/painel.assinatura'
import { Route as AdminSuporteRouteImport } from './routes/admin.suporte'
import { Route as AdminPlanosRouteImport } from './routes/admin.planos'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminFaturacaoRouteImport } from './routes/admin.faturacao'
import { Route as AdminEmpresasRouteImport } from './routes/admin.empresas'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as PainelFacturacaoIndexRouteImport } from './routes/painel.facturacao.index'
import { Route as PainelFacturacaoNovaRouteImport } from './routes/painel.facturacao.nova'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const RgpdRoute = RgpdRouteImport.update({
  id: '/rgpd',
  path: '/rgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const AtualizacoesRoute = AtualizacoesRouteImport.update({
  id: '/atualizacoes',
  path: '/atualizacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PainelSuporteRoute = PainelSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => PainelRoute,
} as any)
const PainelDefinicoesRoute = PainelDefinicoesRouteImport.update({
  id: '/definicoes',
  path: '/definicoes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelClientesRoute = PainelClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelAssinaturaRoute = PainelAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => PainelRoute,
} as any)
const AdminSuporteRoute = AdminSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaturacaoRoute = AdminFaturacaoRouteImport.update({
  id: '/faturacao',
  path: '/faturacao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresasRoute = AdminEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const PainelFacturacaoIndexRoute = PainelFacturacaoIndexRouteImport.update({
  id: '/facturacao/',
  path: '/facturacao/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelFacturacaoNovaRoute = PainelFacturacaoNovaRouteImport.update({
  id: '/facturacao/nova',
  path: '/facturacao/nova',
  getParentRoute: () => PainelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/atualizacoes': typeof AtualizacoesRoute
  '/contactos': typeof ContactosRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/registro': typeof RegistroRoute
  '/rgpd': typeof RgpdRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/faturacao': typeof AdminFaturacaoRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/painel/assinatura': typeof PainelAssinaturaRoute
  '/painel/clientes': typeof PainelClientesRoute
  '/painel/definicoes': typeof PainelDefinicoesRoute
  '/painel/suporte': typeof PainelSuporteRoute
  '/admin/': typeof AdminIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/painel/facturacao/nova': typeof PainelFacturacaoNovaRoute
  '/painel/facturacao/': typeof PainelFacturacaoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atualizacoes': typeof AtualizacoesRoute
  '/contactos': typeof ContactosRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/registro': typeof RegistroRoute
  '/rgpd': typeof RgpdRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/faturacao': typeof AdminFaturacaoRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/painel/assinatura': typeof PainelAssinaturaRoute
  '/painel/clientes': typeof PainelClientesRoute
  '/painel/definicoes': typeof PainelDefinicoesRoute
  '/painel/suporte': typeof PainelSuporteRoute
  '/admin': typeof AdminIndexRoute
  '/painel': typeof PainelIndexRoute
  '/painel/facturacao/nova': typeof PainelFacturacaoNovaRoute
  '/painel/facturacao': typeof PainelFacturacaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/atualizacoes': typeof AtualizacoesRoute
  '/contactos': typeof ContactosRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/registro': typeof RegistroRoute
  '/rgpd': typeof RgpdRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/faturacao': typeof AdminFaturacaoRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/painel/assinatura': typeof PainelAssinaturaRoute
  '/painel/clientes': typeof PainelClientesRoute
  '/painel/definicoes': typeof PainelDefinicoesRoute
  '/painel/suporte': typeof PainelSuporteRoute
  '/admin/': typeof AdminIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/painel/facturacao/nova': typeof PainelFacturacaoNovaRoute
  '/painel/facturacao/': typeof PainelFacturacaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/atualizacoes'
    | '/contactos'
    | '/login'
    | '/painel'
    | '/privacidade'
    | '/registro'
    | '/rgpd'
    | '/sobre'
    | '/termos'
    | '/admin/configuracoes'
    | '/admin/empresas'
    | '/admin/faturacao'
    | '/admin/logs'
    | '/admin/planos'
    | '/admin/suporte'
    | '/painel/assinatura'
    | '/painel/clientes'
    | '/painel/definicoes'
    | '/painel/suporte'
    | '/admin/'
    | '/painel/'
    | '/painel/facturacao/nova'
    | '/painel/facturacao/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atualizacoes'
    | '/contactos'
    | '/login'
    | '/privacidade'
    | '/registro'
    | '/rgpd'
    | '/sobre'
    | '/termos'
    | '/admin/configuracoes'
    | '/admin/empresas'
    | '/admin/faturacao'
    | '/admin/logs'
    | '/admin/planos'
    | '/admin/suporte'
    | '/painel/assinatura'
    | '/painel/clientes'
    | '/painel/definicoes'
    | '/painel/suporte'
    | '/admin'
    | '/painel'
    | '/painel/facturacao/nova'
    | '/painel/facturacao'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/atualizacoes'
    | '/contactos'
    | '/login'
    | '/painel'
    | '/privacidade'
    | '/registro'
    | '/rgpd'
    | '/sobre'
    | '/termos'
    | '/admin/configuracoes'
    | '/admin/empresas'
    | '/admin/faturacao'
    | '/admin/logs'
    | '/admin/planos'
    | '/admin/suporte'
    | '/painel/assinatura'
    | '/painel/clientes'
    | '/painel/definicoes'
    | '/painel/suporte'
    | '/admin/'
    | '/painel/'
    | '/painel/facturacao/nova'
    | '/painel/facturacao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AtualizacoesRoute: typeof AtualizacoesRoute
  ContactosRoute: typeof ContactosRoute
  LoginRoute: typeof LoginRoute
  PainelRoute: typeof PainelRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  RegistroRoute: typeof RegistroRoute
  RgpdRoute: typeof RgpdRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rgpd': {
      id: '/rgpd'
      path: '/rgpd'
      fullPath: '/rgpd'
      preLoaderRoute: typeof RgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atualizacoes': {
      id: '/atualizacoes'
      path: '/atualizacoes'
      fullPath: '/atualizacoes'
      preLoaderRoute: typeof AtualizacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/painel/suporte': {
      id: '/painel/suporte'
      path: '/suporte'
      fullPath: '/painel/suporte'
      preLoaderRoute: typeof PainelSuporteRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/definicoes': {
      id: '/painel/definicoes'
      path: '/definicoes'
      fullPath: '/painel/definicoes'
      preLoaderRoute: typeof PainelDefinicoesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/clientes': {
      id: '/painel/clientes'
      path: '/clientes'
      fullPath: '/painel/clientes'
      preLoaderRoute: typeof PainelClientesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/assinatura': {
      id: '/painel/assinatura'
      path: '/assinatura'
      fullPath: '/painel/assinatura'
      preLoaderRoute: typeof PainelAssinaturaRouteImport
      parentRoute: typeof PainelRoute
    }
    '/admin/suporte': {
      id: '/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AdminSuporteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faturacao': {
      id: '/admin/faturacao'
      path: '/faturacao'
      fullPath: '/admin/faturacao'
      preLoaderRoute: typeof AdminFaturacaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empresas': {
      id: '/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminEmpresasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/painel/facturacao/': {
      id: '/painel/facturacao/'
      path: '/facturacao'
      fullPath: '/painel/facturacao/'
      preLoaderRoute: typeof PainelFacturacaoIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/facturacao/nova': {
      id: '/painel/facturacao/nova'
      path: '/facturacao/nova'
      fullPath: '/painel/facturacao/nova'
      preLoaderRoute: typeof PainelFacturacaoNovaRouteImport
      parentRoute: typeof PainelRoute
    }
  }
}

interface AdminRouteChildren {
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminEmpresasRoute: typeof AdminEmpresasRoute
  AdminFaturacaoRoute: typeof AdminFaturacaoRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminSuporteRoute: typeof AdminSuporteRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminEmpresasRoute: AdminEmpresasRoute,
  AdminFaturacaoRoute: AdminFaturacaoRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminSuporteRoute: AdminSuporteRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PainelRouteChildren {
  PainelAssinaturaRoute: typeof PainelAssinaturaRoute
  PainelClientesRoute: typeof PainelClientesRoute
  PainelDefinicoesRoute: typeof PainelDefinicoesRoute
  PainelSuporteRoute: typeof PainelSuporteRoute
  PainelIndexRoute: typeof PainelIndexRoute
  PainelFacturacaoNovaRoute: typeof PainelFacturacaoNovaRoute
  PainelFacturacaoIndexRoute: typeof PainelFacturacaoIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelAssinaturaRoute: PainelAssinaturaRoute,
  PainelClientesRoute: PainelClientesRoute,
  PainelDefinicoesRoute: PainelDefinicoesRoute,
  PainelSuporteRoute: PainelSuporteRoute,
  PainelIndexRoute: PainelIndexRoute,
  PainelFacturacaoNovaRoute: PainelFacturacaoNovaRoute,
  PainelFacturacaoIndexRoute: PainelFacturacaoIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AtualizacoesRoute: AtualizacoesRoute,
  ContactosRoute: ContactosRoute,
  LoginRoute: LoginRoute,
  PainelRoute: PainelRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  RegistroRoute: RegistroRoute,
  RgpdRoute: RgpdRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
